---
printWidth: 100
tabWidth: 2
# useTabs: true
semi: true
singleQuote: true
quoteProps: as-needed
# jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
# bracketSameLine: true
# jsxBracketSameLine: true
arrowParens: always
# rangeStart: 0
# rangeEnd: Infinity
# parser:
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: lf

overrides:
  - files: '*.{css,scss}'
    options:
      singleQuote: false
